name: IndustrialRevival
version: '${project.version}'
main: org.inr.IndustrialRevival.core.IndustrialRevival
api-version: '1.20'
authors: [mmmjjkx and IndustrialRevival community]
libraries:
  - org.mybatis:mybatis:3.5.16